# Ignore Maven build files
target/
pom.xml.tag
pom.xml.releaseBackup
pom.xml.versionsBackup
pom.xml.next
release.properties

# Ignore IntelliJ IDEA project files
.idea/
*.iml

# Ignore Maven wrapper files
.mvn/
mvnw
mvnw.cmd

# Ignore Kotlin build files
build/

# Ignore logs
*.log

# Ignore temporary files
*.tmp
*.swp
*.swo
*~

# Ignore Kubernetes configuration files
k8s/
