# Name of the workflow and an action title to display in the GitHub UI
name: Deploy Project
run-name: ${{ github.actor }} is deploying the project

# Decides when the workflow gets triggered, this is a "coarse" definition for the whole workflow
# Jobs can refine it further or use the defaults defined here
# List of all events that can be used for triggering workflows:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Run on push to the main branch, and tags in the form v*.*.* eg.: v1.0.0
  push:
    branches:
      - main
    tags:
      - v*.*.*
  # Runs every time a pull request is created, updated, etc. can use "types" to run only on select PR activities
  pull_request:
    branches:
      - main

# Used to make sure that only one workflow in the specified group runs at the same time
concurrency:
  # Define a concurrency group which is then used to determine duplicate workflow runs
  # The second property uses fallback values since not every run is a PR run
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

# Modify access granted to the workflow in the GITHUB_TOKEN
# Mainly used here to give checks a write permission to allow a test run reporter to publish test results
permissions:
  contents: read
  actions: read
  checks: write

# List of jobs that this workflow executes, each job can run on different runners, have different steps, etc.
jobs:
  # Unique identifier for this job, make sure it is unique, you can use the "name" property to give it a more descriptive name
  test-upload-build:
    # This name is displayed in the GitHub UI when the job is running
    name: Build and Validate the Project
    # Reference of which workflow this job should use. We use the same process for building apps with Maven across
    # all of our projects.
    uses: NationalLibraryOfNorway/mlt-workflows/.github/workflows/maven-build-and-upload.yml@main
    # Settings/Inputs/Parameters for the action
    with:
      project-name: ${{ vars.PROJECT_NAME }}
    secrets:
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      VAULT_URL: ${{ secrets.NB_VAULT_URL }}

  # This job builds a Docker image with relevant tags and labels and publishes it to Harbor
  build-publish-image:
    name: Build and publish the Docker Image
    uses: NationalLibraryOfNorway/mlt-workflows/.github/workflows/docker-build-and-push.yml@main
    needs: test-upload-build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    with:
      project-name: ${{ vars.PROJECT_NAME }}
      dockerfile: ./docker/Dockerfile
      artifact-name: packaged-project
    secrets:
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
      VAULT_URL: ${{ secrets.NB_VAULT_URL }}

  # This job deploys the Docker image to the Stage environment
  # It uses a reusable workflow to handle the actual deployment process via ArgoCD
  deploy-to-stage:
    name: Deploy to Stage
    needs: build-publish-image
    if: github.ref == 'refs/heads/main'
    uses: NationalLibraryOfNorway/mlt-workflows/.github/workflows/deploy-to-environment.yml@main
    with:
      project-name: ${{ vars.PROJECT_NAME }}
      environment: stage
      image-tag: sha-${{ github.sha }}
    secrets:
      MLT_ARGO_APP_ID: ${{ secrets.MLT_ARGO_APP_ID }}
      MLT_ARGO_PRIVATE_KEY: ${{ secrets.MLT_ARGO_PRIVATE_KEY }}

  # This job deploys the Docker image to the Production environment
  # It uses a reusable workflow to handle the actual deployment process via ArgoCD
  deploy-to-prod:
    name: Deploy to Prod
    needs: build-publish-image
    if: startsWith(github.ref, 'refs/tags/v')
    uses: NationalLibraryOfNorway/mlt-workflows/.github/workflows/deploy-to-environment.yml@main
    with:
      project-name: ${{ vars.PROJECT_NAME }}
      environment: prod
      image-tag: ${{ needs.build-publish-image.outputs.version }}
    secrets:
      MLT_ARGO_APP_ID: ${{ secrets.MLT_ARGO_APP_ID }}
      MLT_ARGO_PRIVATE_KEY: ${{ secrets.MLT_ARGO_PRIVATE_KEY }}
